"""
Michigan Auto sample_data - drop-in replacement for the sample_data
block at the bottom of cred_scoring_engine.py.

Usage
-----
1. Open  cred_scoring_engine.py
2. Find the block at the very bottom that starts with:
       if __name__ == "__main__":
           sample_data = {
3. Replace that dict with the sample_data dict from this file.
4. Run:  python cred_scoring_engine.py

Built from the 10 raw Power BI metadata CSVs in /Raw Metadata/.
Total reports: 30
"""

sample_data = {
    "report_id": [
        "RPT-001",
        "RPT-002",
        "RPT-003",
        "RPT-004",
        "RPT-005",
        "RPT-006",
        "RPT-007",
        "RPT-008",
        "RPT-009",
        "RPT-010",
        "RPT-011",
        "RPT-012",
        "RPT-013",
        "RPT-014",
        "RPT-015",
        "RPT-016",
        "RPT-017",
        "RPT-018",
        "RPT-019",
        "RPT-020",
        "RPT-021",
        "RPT-022",
        "RPT-023",
        "RPT-024",
        "RPT-025",
        "RPT-026",
        "RPT-027",
        "RPT-028",
        "RPT-029",
        "RPT-030",
    ],

    "report_name": [
        "far pivot report",
        "8:15 kpi dashboard",
        "maintenance work orders",
        "machine downtime analysis",
        "executive kpi summary",
        "planned maintenance schedule",
        "oee trend report",
        "cost centre p&l",
        "headcount by plant",
        "predictive failure scores",
        "supplier quality report",
        "production line throughput",
        "far monthly variance",
        "mttr mtbf analysis",
        "energy consumption kpis",
        "scrap & rework report",
        "asset register",
        "shift handover summary",
        "safety incidents report",
        "inventory & parts tracker",
        "production efficiency",
        "finance dashboard",
        "supply chain kpis",
        "shift performance",
        "customer quality scorecard",
        "hr attrition analysis",
        "dev test report 1",
        "dev test report 2",
        "uat far validation",
        "uat 8:15 validation",
    ],

    "report_description": [
        "far pivot report | dataset: far semantic model",
        "8:15 kpi dashboard | dataset: 8:15 kpi semantic model",
        "maintenance work orders | dataset: maintenance semantic model",
        "machine downtime analysis | dataset: 8:15 kpi semantic model",
        "executive kpi summary | dataset: executive summary dataset",
        "planned maintenance schedule | dataset: maintenance semantic model",
        "oee trend report | dataset: 8:15 kpi semantic model",
        "cost centre p&l | dataset: far semantic model",
        "headcount by plant | dataset: hr semantic model",
        "predictive failure scores | dataset: predictive model dataset",
        "supplier quality report | dataset: supply chain dataset",
        "production line throughput | dataset: 8:15 kpi semantic model",
        "far monthly variance | dataset: far semantic model",
        "mttr mtbf analysis | dataset: maintenance semantic model",
        "energy consumption kpis | dataset: energy dataset",
        "scrap & rework report | dataset: quality dataset",
        "asset register | dataset: maintenance semantic model",
        "shift handover summary | dataset: 8:15 kpi semantic model",
        "safety incidents report | dataset: safety dataset",
        "inventory & parts tracker | dataset: inventory & parts",
        "production efficiency | dataset: production planning",
        "finance dashboard | dataset: finance consolidated",
        "supply chain kpis | dataset: supply chain dataset",
        "shift performance | dataset: shift scheduling",
        "customer quality scorecard | dataset: customer quality",
        "hr attrition analysis | dataset: hr semantic model",
        "dev test report 1 | dataset: dev - far test",
        "dev test report 2 | dataset: dev - 8:15 test",
        "uat far validation | dataset: uat - far",
        "uat 8:15 validation | dataset: uat - 8:15",
    ],

    "source_platform": [
        "power bi",
        "power bi",
        "power bi",
        "power bi",
        "power bi",
        "power bi",
        "power bi",
        "power bi",
        "power bi",
        "power bi",
        "power bi",
        "power bi",
        "power bi",
        "power bi",
        "power bi",
        "power bi",
        "power bi",
        "power bi",
        "power bi",
        "power bi",
        "power bi",
        "power bi",
        "power bi",
        "power bi",
        "power bi",
        "power bi",
        "power bi",
        "power bi",
        "power bi",
        "power bi",
    ],

    "business_domain": [
        "finance",
        "operations",
        "maintenance",
        "production",
        "executive",
        "maintenance",
        "operations",
        "finance",
        "finance",
        "data science",
        "supply chain",
        "production",
        "finance",
        "maintenance",
        "production",
        "production",
        "maintenance",
        "operations",
        "production",
        "maintenance",
        "production",
        "finance",
        "supply chain",
        "production",
        "supply chain",
        "hr",
        "dev/test",
        "dev/test",
        "dev/test",
        "dev/test",
    ],

    "owner_email": [
        "analyst1@michiganauto.com",
        "dev.team@michiganauto.com",
        "smoore@michiganauto.com",
        "analyst1@michiganauto.com",
        "bjackson@michiganauto.com",
        "kwhite@michiganauto.com",
        "danderson@michiganauto.com",
        "ctaylor@michiganauto.com",
        "ds.lead@michiganauto.com",
        "pmartinez@michiganauto.com",
        "mthompson@michiganauto.com",
        "drobinson@michiganauto.com",
        "mthompson@michiganauto.com",
        "finance@michiganauto.com",
        "jbrown@michiganauto.com",
        "maint.mgr@michiganauto.com",
        "analyst1@michiganauto.com",
        "bjackson@michiganauto.com",
        "john.smith@michiganauto.com",
        "pmartinez@michiganauto.com",
        "pmartinez@michiganauto.com",
        "gthomas@michiganauto.com",
        "plee@michiganauto.com",
        "gthomas@michiganauto.com",
        "exec.admin@michiganauto.com",
        "pmartinez@michiganauto.com",
        "lgarcia@michiganauto.com",
        "nadams@michiganauto.com",
        "danderson@michiganauto.com",
        "kwhite@michiganauto.com",
    ],

    "last_accessed_date": [
        "2026-05-25",
        "2026-05-25",
        "2026-05-25",
        "2026-05-25",
        "2026-05-25",
        "2026-05-25",
        "2026-05-25",
        "2026-05-25",
        "2026-05-25",
        "2026-05-25",
        "2026-05-25",
        "2026-05-25",
        "2026-05-25",
        "2026-05-25",
        "2026-05-25",
        "2026-05-25",
        "2026-05-25",
        "2026-05-25",
        "2026-05-25",
        "2026-05-24",
        "2026-05-25",
        "2026-05-25",
        "2026-05-25",
        "2026-05-25",
        "2026-05-25",
        "2026-05-25",
        "2026-05-25",
        "2026-05-25",
        "2026-05-25",
        "2026-05-25",
    ],

    "view_count_90d": [
        236,
        255,
        272,
        245,
        266,
        254,
        239,
        237,
        267,
        237,
        252,
        259,
        227,
        230,
        255,
        251,
        275,
        250,
        256,
        236,
        250,
        277,
        265,
        274,
        271,
        239,
        249,
        239,
        275,
        240,
    ],

    "source_tables": [
        "vw_far_semantic_model",
        "vw_8:15_kpi_semantic_model",
        "vw_maintenance_semantic_model",
        "vw_8:15_kpi_semantic_model",
        "vw_executive_summary_dataset",
        "vw_maintenance_semantic_model",
        "vw_8:15_kpi_semantic_model",
        "vw_far_semantic_model",
        "vw_hr_semantic_model",
        "vw_predictive_model_dataset",
        "vw_supply_chain_dataset",
        "vw_8:15_kpi_semantic_model",
        "vw_far_semantic_model",
        "vw_maintenance_semantic_model",
        "vw_energy_dataset",
        "vw_quality_dataset",
        "vw_maintenance_semantic_model",
        "vw_8:15_kpi_semantic_model",
        "vw_safety_dataset",
        "vw_inventory_&_parts",
        "vw_production_planning",
        "vw_finance_consolidated",
        "vw_supply_chain_dataset",
        "vw_shift_scheduling",
        "vw_customer_quality",
        "vw_hr_semantic_model",
        "vw_dev_-_far_test",
        "vw_dev_-_8:15_test",
        "vw_uat_-_far",
        "vw_uat_-_8:15",
    ],

    "metrics": [
        "actual spend|budget spend|ebitda|ebitda margin %|far cost centre rank|far variance %|mtd far spend|revenue|rolling 12m far spend|total far spend|ytd far spend",
        "actual output|availability %|downtime hours|good parts|oee %|oee target gap|performance %|planned production time|quality rate %|rolling 13m downtime|run time|scrap count|scrap rate %|total parts",
        "actual cost|cost variance %|mtbf (days)|mttr (hours)|planned cost|preventive wo %|work orders closed|work orders open|work orders overdue",
        "actual output|availability %|downtime hours|good parts|oee %|oee target gap|performance %|planned production time|quality rate %|rolling 13m downtime|run time|scrap count|scrap rate %|total parts",
        "",
        "actual cost|cost variance %|mtbf (days)|mttr (hours)|planned cost|preventive wo %|work orders closed|work orders open|work orders overdue",
        "actual output|availability %|downtime hours|good parts|oee %|oee target gap|performance %|planned production time|quality rate %|rolling 13m downtime|run time|scrap count|scrap rate %|total parts",
        "actual spend|budget spend|ebitda|ebitda margin %|far cost centre rank|far variance %|mtd far spend|revenue|rolling 12m far spend|total far spend|ytd far spend",
        "headcount fte|turnover rate %",
        "high risk asset count|predictive failure score",
        "on time delivery %|supplier dppm",
        "actual output|availability %|downtime hours|good parts|oee %|oee target gap|performance %|planned production time|quality rate %|rolling 13m downtime|run time|scrap count|scrap rate %|total parts",
        "actual spend|budget spend|ebitda|ebitda margin %|far cost centre rank|far variance %|mtd far spend|revenue|rolling 12m far spend|total far spend|ytd far spend",
        "actual cost|cost variance %|mtbf (days)|mttr (hours)|planned cost|preventive wo %|work orders closed|work orders open|work orders overdue",
        "energy cost|energy per unit",
        "",
        "actual cost|cost variance %|mtbf (days)|mttr (hours)|planned cost|preventive wo %|work orders closed|work orders open|work orders overdue",
        "actual output|availability %|downtime hours|good parts|oee %|oee target gap|performance %|planned production time|quality rate %|rolling 13m downtime|run time|scrap count|scrap rate %|total parts",
        "near miss count|safety incident rate",
        "",
        "",
        "",
        "on time delivery %|supplier dppm",
        "",
        "",
        "headcount fte|turnover rate %",
        "",
        "",
        "",
        "",
    ],

    "dimensions": [
        "gl drill-through|overview|prior year comp|variance analysis|ytd summary",
        "downtime analysis|kpi overview|machine status|shift summary",
        "completed orders|cost analysis|open orders|schedule view|work order summary",
        "downtime overview|machine detail|pareto analysis",
        "financial summary",
        "compliance status|plant view|schedule overview",
        "machine breakdown",
        "budget vs actual|cost centre view|gl detail|variance",
        "page 1|page 2|page 3",
        "page 2|page 3|page 4",
        "page 2",
        "page 2|page 3",
        "page 2|page 4",
        "page 1",
        "",
        "page 2|page 4",
        "page 1|page 2",
        "page 1|page 2",
        "page 1|page 2|page 3",
        "page 1|page 2|page 3",
        "page 2|page 4",
        "page 1|page 2|page 3|page 4",
        "page 1|page 3|page 4",
        "page 1|page 2|page 3",
        "page 1",
        "page 2|page 3|page 4",
        "page 1|page 2",
        "page 1",
        "page 1|page 3",
        "page 1|page 2|page 3",
    ],

    "report_type": [
        "operational",
        "operational",
        "operational",
        "scheduled",
        "operational",
        "operational",
        "operational",
        "operational",
        "scheduled",
        "operational",
        "operational",
        "operational",
        "scheduled",
        "executive",
        "operational",
        "operational",
        "operational",
        "operational",
        "operational",
        "operational",
        "scheduled",
        "operational",
        "operational",
        "scheduled",
        "executive",
        "operational",
        "ad-hoc",
        "ad-hoc",
        "ad-hoc",
        "ad-hoc",
    ],

    "tags": [
        "none|michigan auto - far reporting",
        "none|michigan auto - 8:15 kpis",
        "none|michigan auto - maintenance",
        "promoted|michigan auto - production",
        "none|michigan auto - executive",
        "none|michigan auto - maintenance",
        "none|michigan auto - 8:15 kpis",
        "none|michigan auto - finance",
        "promoted|michigan auto - finance",
        "none|michigan auto - data science",
        "none|michigan auto - supply chain",
        "none|michigan auto - production",
        "promoted|michigan auto - far reporting",
        "certified|michigan auto - maintenance",
        "none|michigan auto - production",
        "none|michigan auto - production",
        "none|michigan auto - maintenance",
        "none|michigan auto - 8:15 kpis",
        "none|michigan auto - production",
        "none|michigan auto - maintenance",
        "promoted|michigan auto - production",
        "none|michigan auto - finance",
        "none|michigan auto - supply chain",
        "promoted|michigan auto - production",
        "certified|michigan auto - supply chain",
        "none|michigan auto - hr analytics",
        "none|michigan auto - dev",
        "none|michigan auto - dev",
        "none|michigan auto - uat",
        "promoted|michigan auto - uat",
    ],

    "refresh_fail_rate_30d": [
        0.25,
        0.0,
        0.0,
        0.0,
        0.0,
        0.0,
        0.0,
        0.25,
        0.0,
        0.0,
        0.0,
        0.0,
        0.25,
        0.0,
        0.0,
        0.0,
        0.0,
        0.0,
        0.0,
        0.0,
        0.0,
        0.0,
        0.0,
        0.0,
        0.0,
        0.0,
        0.0,
        0.0,
        0.0,
        0.0,
    ],

    "activity_fail_rate_30d": [
        0.0,
        0.214,
        0.0,
        0.0,
        0.0,
        0.0,
        0.0,
        0.0,
        0.0,
        0.053,
        0.0,
        0.0,
        0.0,
        0.059,
        0.0,
        0.083,
        0.0,
        0.029,
        0.05,
        0.0,
        0.0,
        0.0,
        0.0,
        0.125,
        0.05,
        0.0,
        0.0,
        0.0,
        0.0,
        0.0,
    ],

    "edit_count_90d": [
        22,
        22,
        18,
        20,
        22,
        24,
        21,
        29,
        22,
        21,
        26,
        18,
        11,
        20,
        21,
        18,
        20,
        17,
        18,
        15,
        27,
        17,
        15,
        24,
        21,
        24,
        24,
        25,
        23,
        18,
    ],

    "mobile_view_share": [
        0.267,
        0.275,
        0.165,
        0.184,
        0.177,
        0.185,
        0.234,
        0.198,
        0.165,
        0.194,
        0.198,
        0.147,
        0.185,
        0.178,
        0.18,
        0.175,
        0.2,
        0.228,
        0.195,
        0.195,
        0.164,
        0.177,
        0.211,
        0.19,
        0.185,
        0.172,
        0.201,
        0.255,
        0.196,
        0.188,
    ],

    "is_mobile_ready": [
        False,
        False,
        True,
        False,
        False,
        True,
        True,
        True,
        False,
        True,
        False,
        False,
        True,
        False,
        False,
        False,
        True,
        False,
        False,
        True,
        False,
        False,
        False,
        False,
        True,
        True,
        True,
        False,
        True,
        True,
    ],

}
